export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE'
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'

export const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST'
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS'
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE'

export const GET_MEMBER_REQUEST = 'GET_MEMBER_REQUEST'
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS'
export const GET_MEMBER_FAILURE = 'GET_MEMBER_FAILURE'

export const CREATE_MEMBER_REQUEST = 'CREATE_MEMBER_REQUEST'
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS'
export const CREATE_MEMBER_FAILURE = 'CREATE_MEMBER_FAILURE'

export const UPDATE_MEMBER_REQUEST = 'UPDATE_MEMBER_REQUEST'
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS'
export const UPDATE_MEMBER_FAILURE = 'UPDATE_MEMBER_FAILURE'

export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE'

export const GET_SALES_REQUEST = 'GET_SALES_REQUEST'
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS'
export const GET_SALES_FAILURE = 'GET_SALES_FAILURE'

export const GET_SALE_REQUEST = 'GET_SALE_REQUEST'
export const GET_SALE_SUCCESS = 'GET_SALE_SUCCESS'
export const GET_SALE_FAILURE = 'GET_SALE_FAILURE'

export const CREATE_SALE_REQUEST = 'CREATE_SALE_REQUEST'
export const CREATE_SALE_SUCCESS = 'CREATE_SALE_SUCCESS'
export const CREATE_SALE_FAILURE = 'CREATE_SALE_FAILURE'

export const UPDATE_SALE_REQUEST = 'UPDATE_SALE_REQUEST'
export const UPDATE_SALE_SUCCESS = 'UPDATE_SALE_SUCCESS'
export const UPDATE_SALE_FAILURE = 'UPDATE_SALE_FAILURE'

export const DELETE_SALE_REQUEST = 'DELETE_SALE_REQUEST'
export const DELETE_SALE_SUCCESS = 'DELETE_SALE_SUCCESS'
export const DELETE_SALE_FAILURE = 'DELETE_SALE_FAILURE'

export const GET_MEMBER_INCOMES_REQUEST = 'GET_MEMBER_INCOMES_REQUEST'
export const GET_MEMBER_INCOMES_SUCCESS = 'GET_MEMBER_INCOMES_SUCCESS'
export const GET_MEMBER_INCOMES_FAILURE = 'GET_MEMBER_INCOMES_FAILURE'

export const GET_MEMBER_POINTS_REQUEST = 'GET_MEMBER_POINTS_REQUEST'
export const GET_MEMBER_POINTS_SUCCESS = 'GET_MEMBER_POINTS_SUCCESS'
export const GET_MEMBER_POINTS_FAILURE = 'GET_MEMBER_POINTS_FAILURE'

export const GET_MEMBER_SALES_REQUEST = 'GET_MEMBER_SALES_REQUEST'
export const GET_MEMBER_SALES_SUCCESS = 'GET_MEMBER_SALES_SUCCESS'
export const GET_MEMBER_SALES_FAILURE = 'GET_MEMBER_SALES_FAILURE'

export const GET_MEMBER_REFERS_REQUEST = 'GET_MEMBER_REFERS_REQUEST'
export const GET_MEMBER_REFERS_SUCCESS = 'GET_MEMBER_REFERS_SUCCESS'
export const GET_MEMBER_REFERS_FAILURE = 'GET_MEMBER_REFERS_FAILURE'

export const GET_MEMBER_WITHDRAWALS_REQUEST = 'GET_MEMBER_WITHDRAWALS_REQUEST'
export const GET_MEMBER_WITHDRAWALS_SUCCESS = 'GET_MEMBER_WITHDRAWALS_SUCCESS'
export const GET_MEMBER_WITHDRAWALS_FAILURE = 'GET_MEMBER_WITHDRAWALS_FAILURE'

export const GET_WITHDRAWALS_REQUEST = 'GET_WITHDRAWALS_REQUEST'
export const GET_WITHDRAWALS_SUCCESS = 'GET_WITHDRAWALS_SUCCESS'
export const GET_WITHDRAWALS_FAILURE = 'GET_WITHDRAWALS_FAILURE'

export const GET_WITHDRAWAL_REQUEST = 'GET_WITHDRAWAL_REQUEST'
export const GET_WITHDRAWAL_SUCCESS = 'GET_WITHDRAWAL_SUCCESS'
export const GET_WITHDRAWAL_FAILURE = 'GET_WITHDRAWAL_FAILURE'

export const CREATE_WITHDRAWAL_REQUEST = 'CREATE_WITHDRAWAL_REQUEST'
export const CREATE_WITHDRAWAL_SUCCESS = 'CREATE_WITHDRAWAL_SUCCESS'
export const CREATE_WITHDRAWAL_FAILURE = 'CREATE_WITHDRAWAL_FAILURE'

export const UPDATE_WITHDRAWAL_REQUEST = 'UPDATE_WITHDRAWAL_REQUEST'
export const UPDATE_WITHDRAWAL_SUCCESS = 'UPDATE_WITHDRAWAL_SUCCESS'
export const UPDATE_WITHDRAWAL_FAILURE = 'UPDATE_WITHDRAWAL_FAILURE'

export const DELETE_WITHDRAWAL_REQUEST = 'DELETE_WITHDRAWAL_REQUEST'
export const DELETE_WITHDRAWAL_SUCCESS = 'DELETE_WITHDRAWAL_SUCCESS'
export const DELETE_WITHDRAWAL_FAILURE = 'DELETE_WITHDRAWAL_FAILURE'

export const PROCESS_WITHDRAWAL_REQUEST = 'PROCESS_WITHDRAWAL_REQUEST'
export const PROCESS_WITHDRAWAL_SUCCESS = 'PROCESS_WITHDRAWAL_SUCCESS'
export const PROCESS_WITHDRAWAL_FAILURE = 'PROCESS_WITHDRAWAL_FAILURE'

export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE'

export const CREATE_SETTING_REQUEST = 'CREATE_SETTING_REQUEST'
export const CREATE_SETTING_SUCCESS = 'CREATE_SETTING_SUCCESS'
export const CREATE_SETTING_FAILURE = 'CREATE_SETTING_FAILURE'

export const UPDATE_SETTINGS_REQUEST = 'UPDATE_SETTINGS_REQUEST'
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS'
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE'

export const DELETE_SETTING_REQUEST = 'DELETE_SETTING_REQUEST'
export const DELETE_SETTING_SUCCESS = 'DELETE_SETTING_SUCCESS'
export const DELETE_SETTING_FAILURE = 'DELETE_SETTING_FAILURE'

export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST'
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS'
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const SAVE_PROFILE_REQUEST = 'SAVE_PROFILE_REQUEST'
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS'
export const SAVE_PROFILE_FAILURE = 'SAVE_PROFILE_FAILURE'

export const GET_INCOMES_REQUEST = 'GET_INCOMES_REQUEST'
export const GET_INCOMES_SUCCESS = 'GET_INCOMES_SUCCESS'
export const GET_INCOMES_FAILURE = 'GET_INCOMES_FAILURE'

export const GET_POINTS_REQUEST = 'GET_POINTS_REQUEST'
export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS'
export const GET_POINTS_FAILURE = 'GET_POINTS_FAILURE'

export const GET_POINTREDEEMS_REQUEST = 'GET_POINTREDEEMS_REQUEST'
export const GET_POINTREDEEMS_SUCCESS = 'GET_POINTREDEEMS_SUCCESS'
export const GET_POINTREDEEMS_FAILURE = 'GET_POINTREDEEMS_FAILURE'

export const GET_POINTREDEEM_REQUEST = 'GET_POINTREDEEM_REQUEST'
export const GET_POINTREDEEM_SUCCESS = 'GET_POINTREDEEM_SUCCESS'
export const GET_POINTREDEEM_FAILURE = 'GET_POINTREDEEM_FAILURE'

export const PROCESS_POINTREDEEM_REQUEST = 'PROCESS_POINTREDEEM_REQUEST'
export const PROCESS_POINTREDEEM_SUCCESS = 'PROCESS_POINTREDEEM_SUCCESS'
export const PROCESS_POINTREDEEM_FAILURE = 'PROCESS_POINTREDEEM_FAILURE'

export const GET_MEMBER_POINTREDEEMS_REQUEST = 'GET_MEMBER_POINTREDEEMS_REQUEST'
export const GET_MEMBER_POINTREDEEMS_SUCCESS = 'GET_MEMBER_POINTREDEEMS_SUCCESS'
export const GET_MEMBER_POINTREDEEMS_FAILURE = 'GET_MEMBER_POINTREDEEMS_FAILURE'

export const CREATE_POINTREDEEM_REQUEST = 'CREATE_POINTREDEEM_REQUEST'
export const CREATE_POINTREDEEM_SUCCESS = 'CREATE_POINTREDEEM_SUCCESS'
export const CREATE_POINTREDEEM_FAILURE = 'CREATE_POINTREDEEM_FAILURE'

export const CHECKED_ANNOUNCEMENT_REQUEST = 'CHECKED_ANNOUNCEMENT_REQUEST'
export const CHECKED_ANNOUNCEMENT_SUCCESS = 'CHECKED_ANNOUNCEMENT_SUCCESS'
export const CHECKED_ANNOUNCEMENT_FAILURE = 'CHECKED_ANNOUNCEMENT_FAILURE'

export const GET_ANNOUNCEMENTS_REQUEST = 'GET_ANNOUNCEMENTS_REQUEST'
export const GET_ANNOUNCEMENTS_SUCCESS = 'GET_ANNOUNCEMENTS_SUCCESS'
export const GET_ANNOUNCEMENTS_FAILURE = 'GET_ANNOUNCEMENTS_FAILURE'

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST'
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS'
export const DELETE_ANNOUNCEMENT_FAILURE = 'DELETE_ANNOUNCEMENT_FAILURE'

export const GET_ANNOUNCEMENT_REQUEST = 'GET_ANNOUNCEMENT_REQUEST'
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS'
export const GET_ANNOUNCEMENT_FAILURE = 'GET_ANNOUNCEMENT_FAILURE'

export const UPDATE_ANNOUNCEMENT_REQUEST = 'UPDATE_ANNOUNCEMENT_REQUEST'
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS'
export const UPDATE_ANNOUNCEMENT_FAILURE = 'UPDATE_ANNOUNCEMENT_FAILURE'

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST'
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS'
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE'

export const REGISTER_MEMBER_REQUEST = 'REGISTER_MEMBER_REQUEST'
export const REGISTER_MEMBER_SUCCESS = 'REGISTER_MEMBER_SUCCESS'
export const REGISTER_MEMBER_FAILURE = 'REGISTER_MEMBER_FAILURE'

export const UPDATE_ANNOUNCEMENTSTATUS_REQUEST = 'UPDATE_ANNOUNCEMENTSTATUS_REQUEST'
export const UPDATE_ANNOUNCEMENTSTATUS_SUCCESS = 'UPDATE_ANNOUNCEMENTSTATUS_SUCCESS'
export const UPDATE_ANNOUNCEMENTSTATUS_FAILURE = 'UPDATE_ANNOUNCEMENTSTATUS_FAILURE'

export const GET_POINTITEMS_REQUEST = 'GET_POINTITEMS_REQUEST'
export const GET_POINTITEMS_SUCCESS = 'GET_POINTITEMS_SUCCESS'
export const GET_POINTITEMS_FAILURE = 'GET_POINTITEMS_FAILURE'

export const GET_POINTITEM_REQUEST = 'GET_POINTITEM_REQUEST'
export const GET_POINTITEM_SUCCESS = 'GET_POINTITEM_SUCCESS'
export const GET_POINTITEM_FAILURE = 'GET_POINTITEM_FAILURE'

export const CREATE_POINTITEM_REQUEST = 'CREATE_POINTITEM_REQUEST'
export const CREATE_POINTITEM_SUCCESS = 'CREATE_POINTITEM_SUCCESS'
export const CREATE_POINTITEM_FAILURE = 'CREATE_POINTITEM_FAILURE'

export const UPDATE_POINTITEM_REQUEST = 'UPDATE_POINTITEM_REQUEST'
export const UPDATE_POINTITEM_SUCCESS = 'UPDATE_POINTITEM_SUCCESS'
export const UPDATE_POINTITEM_FAILURE = 'UPDATE_POINTITEM_FAILURE'

export const DELETE_POINTITEM_REQUEST = 'DELETE_POINTITEM_REQUEST'
export const DELETE_POINTITEM_SUCCESS = 'DELETE_POINTITEM_SUCCESS'
export const DELETE_POINTITEM_FAILURE = 'DELETE_POINTITEM_FAILURE'

export const GET_MEMBER_POINTSALES_REQUEST = 'GET_MEMBER_POINTSALES_REQUEST'
export const GET_MEMBER_POINTSALES_SUCCESS = 'GET_MEMBER_POINTSALES_SUCCESS'
export const GET_MEMBER_POINTSALES_FAILURE = 'GET_MEMBER_POINTSALES_FAILURE'

export const GET_POINTSALES_REQUEST = 'GET_POINTSALES_REQUEST'
export const GET_POINTSALES_SUCCESS = 'GET_POINTSALES_SUCCESS'
export const GET_POINTSALES_FAILURE = 'GET_POINTSALES_FAILURE'

export const GET_POINTSALE_REQUEST = 'GET_POINTSALE_REQUEST'
export const GET_POINTSALE_SUCCESS = 'GET_POINTSALE_SUCCESS'
export const GET_POINTSALE_FAILURE = 'GET_POINTSALE_FAILURE'

export const PROCESS_POINTSALE_REQUEST = 'PROCESS_POINTSALE_REQUEST'
export const PROCESS_POINTSALE_SUCCESS = 'PROCESS_POINTSALE_SUCCESS'
export const PROCESS_POINTSALE_FAILURE = 'PROCESS_POINTSALE_FAILURE'

export const CREATE_POINTSALE_REQUEST = 'CREATE_POINTSALE_REQUEST'
export const CREATE_POINTSALE_SUCCESS = 'CREATE_POINTSALE_SUCCESS'
export const CREATE_POINTSALE_FAILURE = 'CREATE_POINTSALE_FAILURE'